dns:
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  enabled: true
  ipv6: false
  listen: 0.0.0.0:1053
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7890
mode: Rule
proxies:
- cipher: aes-128-gcm
  name: 'å®˜ç½‘: landing.ouonetwork.com'
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48778
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: å¦‚æ— æ³•æ›´æ–°,è¯·ä»å®˜ç½‘æ‹‰å–æœ€æ–°è®¢é˜…
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48778
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡­ğŸ‡° Hong Kong 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48778
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡­ğŸ‡° Hong Kong 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48777
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡­ğŸ‡° Hong Kong 03
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48775
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡­ğŸ‡° Hong Kong 04
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 42004
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡­ğŸ‡° Hong Kong 05
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 42003
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ Taiwan 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48595
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ Taiwan 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48596
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ Taiwan 03
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48597
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ Taiwan 04
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48598
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡¼ Taiwan 05
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48599
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¸ğŸ‡¬ Singapore 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 48890
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¸ğŸ‡¬ Singapore 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 20909
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¸ğŸ‡¬ Singapore 03
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 20910
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¸ğŸ‡¬ Singapore 04
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 20911
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¸ğŸ‡¬ Singapore 05
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 20912
  server: n1eubce2cbv.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µ Japan 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35000
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µ Japan 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 38000
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µ Japan 03
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35004
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µ Japan 04
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35006
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µ Japan 05
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35007
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ United States 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35027
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ United States 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 34010
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ United States 03
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35016
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ United States 04
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35018
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸ United States 05
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35015
  server: s1dnfoevra3dx.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡©ğŸ‡ª Germany 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 38305
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡©ğŸ‡ª Germany 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 30684
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¬ğŸ‡§ Britain 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 22398
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¬ğŸ‡§ Britain 02
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 25520
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡±ğŸ‡º Luxembourg 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 30735
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¦ğŸ‡· Argentina 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 35011
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¹ğŸ‡· Turkey 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 53697
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡®ğŸ‡³ India 01
  password: 531d7206-a7c9-4147-ba4a-984dacfdb4de
  port: 53690
  server: 581f0676f6cbbfcf.h5dg9l1jwpczvs91dekk.pw
  type: ss
  udp: true
proxy-groups:
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png
  include-all: false
  name: PROXY
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  type: select
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘|Argent|Germ|Britain|India|Luxem
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png
  include-all: true
  interval: 150
  name: è‡ªåŠ¨é€‰æ‹©
  tolerance: 50
  type: url-test
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/OpenAI.png
  name: å›½å¤–AI
  proxies:
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  type: select
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png
  name: ç”µæŠ¥æœåŠ¡
  proxies:
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  type: select
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png
  name: è°·æ­ŒæœåŠ¡
  proxies:
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  type: select
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  filter: (?i)é¦™æ¸¯|Hong Kong|HK|ğŸ‡­ğŸ‡°
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png
  include-all: true
  interval: 300
  name: é¦™æ¸¯èŠ‚ç‚¹
  tolerance: 50
  type: url-test
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  filter: (?i)æ–°åŠ å¡|Singapore|ğŸ‡¸ğŸ‡¬
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png
  include-all: true
  interval: 300
  name: æ–°åŠ å¡èŠ‚ç‚¹
  tolerance: 50
  type: url-test
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  filter: (?i)æ—¥æœ¬|Japan|ğŸ‡¯ğŸ‡µ
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png
  include-all: true
  interval: 300
  name: æ—¥æœ¬èŠ‚ç‚¹
  tolerance: 50
  type: url-test
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  filter: (?i)ç¾å›½|USA|ğŸ‡ºğŸ‡¸
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png
  include-all: true
  interval: 300
  name: ç¾å›½èŠ‚ç‚¹
  tolerance: 50
  type: url-test
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  filter: (?i)å°æ¹¾|TW|ğŸ‡¹ğŸ‡¼|tw|taiwan|tai wan
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/TW.png
  include-all: true
  interval: 300
  name: å°æ¹¾èŠ‚ç‚¹
  tolerance: 50
  type: url-test
- exclude-filter: (?i)GB|æµé‡|åˆ°æœŸ|é‡ç½®|å®˜ç½‘
  icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png
  include-all: true
  name: GLOBAL
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  type: select
rule-providers:
  bard:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/bard.yaml
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BardAI/BardAI.yaml
  bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/bing.yaml
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
  claude:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/claude.yaml
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
  cn_domain:
    behavior: domain
    format: yaml
    interval: 86400
    path: ./ruleset/cn_domain.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
  cn_ip:
    behavior: ipcidr
    format: yaml
    interval: 86400
    path: ./ruleset/cn_ip.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
  copilot:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/copilot.yaml
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
  geolocation-!cn:
    behavior: domain
    format: yaml
    interval: 86400
    path: ./ruleset/geolocation-!cn.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml
  google_domain:
    behavior: domain
    format: yaml
    interval: 86400
    path: ./ruleset/google_domain.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml
  google_ip:
    behavior: ipcidr
    format: yaml
    interval: 86400
    path: ./ruleset/google_ip.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml
  openai:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/openai.yaml
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
  private:
    behavior: domain
    format: yaml
    interval: 86400
    path: ./ruleset/private.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
  telegram_domain:
    behavior: domain
    format: yaml
    interval: 86400
    path: ./ruleset/telegram_domain.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
  telegram_ip:
    behavior: ipcidr
    format: yaml
    interval: 86400
    path: ./ruleset/telegram_ip.yaml
    type: http
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml
rules:
- RULE-SET,private,DIRECT
- RULE-SET,bing,å›½å¤–AI
- RULE-SET,copilot,å›½å¤–AI
- RULE-SET,bard,å›½å¤–AI
- RULE-SET,openai,å›½å¤–AI
- RULE-SET,claude,å›½å¤–AI
- RULE-SET,telegram_domain,ç”µæŠ¥æœåŠ¡
- RULE-SET,telegram_ip,ç”µæŠ¥æœåŠ¡
- RULE-SET,google_domain,è°·æ­ŒæœåŠ¡
- RULE-SET,google_ip,è°·æ­ŒæœåŠ¡
- RULE-SET,geolocation-!cn,PROXY
- RULE-SET,cn_domain,DIRECT
- RULE-SET,cn_ip,DIRECT
- MATCH,PROXY
